# Generated by Django 3.2.25 on 2025-02-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereadstatus',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messagereadstatus',
            name='read_at',
            field=models.DateTimeField(),
        ),
    ]
