# Generated by Django 3.2.25 on 2025-02-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_auto_20250227_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereadstatus',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
