version: '3'
 
services:
  web:
    build: .
    container_name: isi-tech
    image: isi-tech
    command:
      bash -c "
      sleep 5
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB={POSTGRES_DB}
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgresql/backup.sql:/backup.sql
      - ./docker/postgresql/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]


volumes:
  postgres_data:
